### PR TITLE
Develop ecu checksum fixes

### PR DESCRIPTION
**Pull request by silviu-toderita**
Troubleshooted a bug that Valentino and I experienced yesterday where checksum of incoming ECU data would often be wrong. Discovered that it's only wrong when header is incorrect, which is OK, moved checksum check after header check and cleaned up some other parts of SensorEcu (largely sloppy coding on my part from last year).

### CODE REVIEW

**Review by cosparks — APPROVED** [review]
I always thought that the checksum was the sum of all the bits, not Bytes.  This makes sense too, but it's kind of funny that in the end you're likely to get an overflowed value.

Looks good!

**Comment by silviu-toderita** [comment]
> I always thought that the checksum was the sum of all the bits, not Bytes. This makes sense too, but it's kind of funny that in the end you're likely to get an overflowed value.
> 
> Looks good!

I'm not sure how a checksum is usually supposed to work, but in this case Valentino just looked at the documentation for the ECU and it said just add up the bytes. 

Overflowing the value isn't as big of a deal as it seems, because you'll catch an error unless the sum is off by a multiple of exactly 256. Even though it's possible, it's unlikely.

**Comment by cosparks** [comment]
Is it possible that the serial buffer has > 27 Bytes, including an ECU message, but the header is in the wrong place?

Like the first 5 bytes in the buffer are:
0x00 0x00 0x80 0x8F 0xEA ...

**Comment by silviu-toderita** [comment]
> Is it possible that the serial buffer has > 27 Bytes, including an ECU message, but the header is in the wrong place?
> 
> Like the first 5 bytes in the buffer are: 0x00 0x00 0x80 0x8F 0xEA ...

Yes I think that's likely what's happening. If handle doesn't run often enough, it will get a 28th or 29th byte in the buffer and the header will appear wrong based on the check we're doing. When that happens, currently we flush the serial buffer and hope next time we catch it at the right moment. At the moment, it's still receiving *most* messages from the ECU, but it's not receiving all 10 per second that the ECU is sending out. Maybe 5-6 on average. It's a crude implementation, and we can look at improving it by scanning the buffer for the header when it has > 27 bytes. 

@valentino-jaber

**Pull request merged**
