### PR TITLE
Developing TinyBMS Unit Tests

### PR DESCRIPTION
**Pull request by valentino-jaber**
This PR aims to add unit tests for TinyBMS, as well as enhance clarity of macros and naming conventions.

### CODE REVIEW

**Comment by silviu-toderita** [comment]
Looks good! Why are the tests failing on Github? Are they unfinished, or did you uncover some bugs with the code?

**Comment by valentino-jaber** [comment]
> Looks good! Why are the tests failing on Github? Are they unfinished, or did you uncover some bugs with the code?

Ah just unfinished. They first commit was just for some templating. The test failure logs were as expected.

**Comment by cosparks** [comment]
I'm going to close this PR for now

**Comment by cosparks** [comment]
I went ahead and threw in some tests.  Could do more but I think it's fairly comprehensive.

Good to go whenever, if one of you guys wanted to do a sanity check

**Review by valentino-jaber — COMMENTED** [review]
Looks good! Its pretty comprehensive I agree!

**Review by cosparks — APPROVED** [review]

**Pull request merged**
